[package]
name = "torch-test"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
rust-bert = "0.23.0"
tch = "0.17.0"
clap = { version = "4.5.37", features = ["derive"] }
nom = "8.0.0"
soa_derive = "0.14.0"